server:
  port: 8080
logging:
  path: logs
  file: mylog.log

spring:
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&characterEncoding=utf8
    username: root
    password: "@zz9423!!!"

mybatis:
  type-aliases-package: medol
  mapper-locations:
    - mapper/*

